version: 2
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --all-extras --group docs --link-mode=copy

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html
