name: Vulnerability Report
description: Report vulnerabilities
labels: unconfirmed vulnerability
assignees: BobDotCom,Lulalaby,CodeWithSwastik
body:
  - type: markdown
    attributes:
      value: >
        Thanks for taking the time to fill out a vulnerability report.
        If you want real-time support, consider joining our Discord at https://pycord.dev/discord instead.

        Please note that this form is for vulnerability reports only!
  - type: textarea
    attributes:
      label: Summary
      description: A simple summary of your vulnerability report
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: >
         What you did to make it happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Minimal Reproducible Code
      description: >
        A short snippet of code that showcases the vulnerability.
      render: python
  - type: textarea
    attributes:
      label: System Information
      description: >
        Run `python -m discord -v` and paste this information below.

        This command required v1.1.0 or higher of the library. If this errors out then show some basic
        information involving your system such as operating system and Python version.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Checklist
      description: >
        Let's make sure you've properly done due dilligence when reporting this issue!
      options:
        - label: I have searched the open issues for duplicates.
          required: true
        - label: I have shown the entire steps to reproduce the vulnerability.
          required: true
        - label: I have removed my token from display, if visible.
          required: true
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
