name: Type Check and Lint
on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requirements-dev.txt
      - name: Setup cache
        id: cache-pylint
        uses: actions/cache@v3
        with:
          path: .pylint.d
          key: pylint
      - name: Analyse code with pylint
        run: |
          pylint discord/ --exit-zero
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: "pip"
          cache-dependency-path: "requirements-dev.txt"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Setup cache
        id: cache-mypy
        uses: actions/cache@v3
        with:
          path: .mypy_cache
          key: mypy
      - name: Make mypy cache directory if cache miss
        if: steps.cache-mypy.outputs.cache-hit != 'true'
        run: mkdir --parents --verbose .mypy_cache
      - name: Run type checks with Mypy
        run: mypy --non-interactive discord/
