name: "Auto Approve"

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    # Bot IDs:
    # - renovate[bot]: 29139614
    # - dependabot[bot]: 49699333
    # - pre-commit-ci[bot]: 66853113
    # - crowdin-bot: 58779643
    # - NyuwBot: 106019021
    if:
      ${{
        github.event.pull_request.user.id == 29139614 ||
        github.event.pull_request.user.id == 49699333 ||
        github.event.pull_request.user.id == 66853113 ||
        github.event.pull_request.user.id == 58779643 ||
        github.event.pull_request.user.id == 106019021
      }}
    continue-on-error: true
    steps:
      - name: "Auto Approve"
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: "Enable Auto Merge"
        if: ${{ always() }}
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
