name: pytest
on: [pull_request, push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pytest pytest-asyncio -r requirements.txt
      - run: pytest
